//! Tile execution helper for native backend subprocess communication.
//!
//! This module provides helper functions that user projects can call from their
//! program entrypoint to handle tile execution requests from the raster CLI's
//! native backend, and to parse program input arguments.

use serde::de::DeserializeOwned;

use raster_runtime::input;

/// Parse the program input from the `--input` argument and deserialize it.
///
/// This function is used by the program entrypoint wrapper generated by
/// `#[raster::sequence]` to parse input arguments passed via the command line.
/// The private input should be a JSON value.
///
/// # Example
///
/// ```bash
/// # For a String input:
/// cargo run -- --input '"Hello"'
///
/// # For a number:
/// cargo run -- --input '42'
///
/// # For a tuple (multiple parameters):
/// cargo run -- --input '["Hello", 42]'
/// ```
///
/// # Returns
///
/// Returns `Some(T)` if the `--input` argument was found and successfully deserialized.
/// Returns `None` if no `--input` argument was found or deserialization failed.
pub fn parse_program_input<T: DeserializeOwned + core::fmt::Debug>() -> Option<T> {
    input::parse_program_input()
}
